import { useState, useRef } from 'react';
import { motion } from 'framer-motion';
import { TrendingUp, Eye, Heart, Share2, ArrowUpRight, Download, Loader2 } from 'lucide-react';
import { 
  AreaChart, 
  Area, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer,
  BarChart,
  Bar
} from 'recharts';
import { useAnalyticsStore, usePublishedPosts } from '../store';
import type { Platform } from '../types';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

const platformColors: Record<Platform, string> = {
  linkedin: '#0077b5',
  twitter: '#1da1f2',
  instagram: '#e4405f',
  facebook: '#1877f2',
  tiktok: '#000000',
  youtube: '#ff0000',
  snapchat: '#fffc00',
};

const container = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.1 } }
};

const item = {
  hidden: { opacity: 0, y: 20 },
  show: { opacity: 1, y: 0 }
};

export default function Analytics() {
  const [isExporting, setIsExporting] = useState(false);
  const analyticsRef = useRef<HTMLDivElement>(null);
  const { analytics } = useAnalyticsStore();
  const publishedPosts = usePublishedPosts();

  const formatNumber = (num: number) => {
    if (num >= 1000000) return (num / 1000000).toFixed(1) + 'M';
    if (num >= 1000) return (num / 1000).toFixed(1) + 'K';
    return num.toString();
  };

  const topPerformingPosts = [...publishedPosts]
    .sort((a, b) => (b.engagement.likes + b.engagement.views + b.engagement.shares) - (a.engagement.likes + a.engagement.views + a.engagement.shares))
    .slice(0, 5);

  const handleExportPDF = async () => {
    if (!analyticsRef.current) return;
    setIsExporting(true);
    
    try {
      const canvas = await html2canvas(analyticsRef.current, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#0a0a1a',
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

      // Add header
      pdf.setFillColor(139, 92, 246);
      pdf.rect(0, 0, pdfWidth, 20, 'F');
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(16);
      pdf.text('ContentSphere Analytics Report', 10, 13);
      pdf.setFontSize(10);
      pdf.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), pdfWidth - 50, 13);

      // Add content
      pdf.addImage(imgData, 'PNG', 0, 25, pdfWidth, pdfHeight);

      // Add footer
      pdf.setTextColor(156, 163, 175);
      pdf.setFontSize(8);
      pdf.text('Generated by ContentSphere AI', 10, pdf.internal.pageSize.getHeight() - 10);
      pdf.text('Page 1', pdfWidth - 20, pdf.internal.pageSize.getHeight() - 10);

      pdf.save(`ContentSphere_Analytics_${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (error) {
      console.error('Export error:', error);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <motion.div 
      variants={container}
      initial="hidden"
      animate="show"
      className="space-y-6"
    >
      {/* Header */}
      <motion.div variants={item} className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-white">Analytics & Insights</h1>
          <p className="text-gray-400 mt-1">Track your content performance</p>
        </div>
        <button 
          onClick={handleExportPDF}
          disabled={isExporting}
          className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-gray-300 transition-colors disabled:opacity-50"
        >
          {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
          {isExporting ? 'Exporting...' : 'Export PDF'}
        </button>
      </motion.div>

      {/* Stats Overview */}
      <motion.div variants={item} className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white/5 backdrop-blur-xl rounded-2xl border border-white/10 p-5">
          <div className="flex items-center justify-between mb-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500 to-cyan-600 flex items-center justify-center">
              <TrendingUp className="w-5 h-5 text-white" />
            </div>
            <span className="text-green-400 text-sm font-medium flex items-center gap-1">
              <ArrowUpRight className="w-3 h-3" />
              +12.8%
            </span>
          </div>
          <p className="text-gray-400 text-sm">Total Posts</p>
          <p className="text-2xl font-bold text-white mt-1">{analytics.totalPosts}</p>
        </div>

        <div className="bg-white/5 backdrop-blur-xl rounded-2xl border border-white/10 p-5">
          <div className="flex items-center justify-between mb-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-pink-500 to-rose-600 flex items-center justify-center">
              <Heart className="w-5 h-5 text-white" />
            </div>
            <span className="text-green-400 text-sm font-medium flex items-center gap-1">
              <ArrowUpRight className="w-3 h-3" />
              +18.2%
            </span>
          </div>
          <p className="text-gray-400 text-sm">Total Engagement</p>
          <p className="text-2xl font-bold text-white mt-1">{formatNumber(analytics.totalEngagement)}</p>
        </div>

        <div className="bg-white/5 backdrop-blur-xl rounded-2xl border border-white/10 p-5">
          <div className="flex items-center justify-between mb-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center">
              <Eye className="w-5 h-5 text-white" />
            </div>
            <span className="text-green-400 text-sm font-medium flex items-center gap-1">
              <ArrowUpRight className="w-3 h-3" />
              +25.4%
            </span>
          </div>
          <p className="text-gray-400 text-sm">Total Views</p>
          <p className="text-2xl font-bold text-white mt-1">128.5K</p>
        </div>

        <div className="bg-white/5 backdrop-blur-xl rounded-2xl border border-white/10 p-5">
          <div className="flex items-center justify-between mb-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-amber-500 to-orange-600 flex items-center justify-center">
              <Share2 className="w-5 h-5 text-white" />
            </div>
            <span className="text-green-400 text-sm font-medium flex items-center gap-1">
              <ArrowUpRight className="w-3 h-3" />
              +15.7%
            </span>
          </div>
          <p className="text-gray-400 text-sm">Growth Rate</p>
          <p className="text-2xl font-bold text-white mt-1">{analytics.growthRate}%</p>
        </div>
      </motion.div>

      {/* Charts Row */}
      <div ref={analyticsRef} className="space-y-6">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Engagement Over Time */}
          <motion.div variants={item} className="bg-white/5 backdrop-blur-xl rounded-2xl border border-white/10 p-6">
            <h3 className="text-lg font-semibold text-white mb-4">Engagement Over Time</h3>
            <div className="h-72">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={analytics.weeklyData}>
                  <defs>
                    <linearGradient id="colorEngagementLikes" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#ec4899" stopOpacity={0.3}/>
                      <stop offset="95%" stopColor="#ec4899" stopOpacity={0}/>
                    </linearGradient>
                    <linearGradient id="colorEngagementComments" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#8b5cf6" stopOpacity={0.3}/>
                      <stop offset="95%" stopColor="#8b5cf6" stopOpacity={0}/>
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="#ffffff10" />
                  <XAxis dataKey="day" stroke="#6b7280" fontSize={12} />
                  <YAxis stroke="#6b7280" fontSize={12} />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: '#1f2937', 
                      border: '1px solid #374151',
                      borderRadius: '12px'
                    }}
                    labelStyle={{ color: '#fff' }}
                  />
                  <Area 
                    type="monotone" 
                    dataKey="likes" 
                    stroke="#ec4899" 
                    fillOpacity={1} 
                    fill="url(#colorEngagementLikes)" 
                    name="Likes"
                  />
                  <Area 
                    type="monotone" 
                    dataKey="comments" 
                    stroke="#8b5cf6" 
                    fillOpacity={1} 
                    fill="url(#colorEngagementComments)" 
                    name="Comments"
                  />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </motion.div>

          {/* Platform Performance */}
          <motion.div variants={item} className="bg-white/5 backdrop-blur-xl rounded-2xl border border-white/10 p-6">
            <h3 className="text-lg font-semibold text-white mb-4">Platform Performance</h3>
            <div className="h-72">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={analytics.platformBreakdown} layout="vertical">
                  <CartesianGrid strokeDasharray="3 3" stroke="#ffffff10" />
                  <XAxis type="number" stroke="#6b7280" fontSize={12} />
                  <YAxis type="category" dataKey="platform" stroke="#6b7280" fontSize={12} width={60} />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: '#1f2937', 
                      border: '1px solid #374151',
                      borderRadius: '12px'
                    }}
                  />
                  <Bar dataKey="posts" fill="#8b5cf6" radius={[0, 4, 4, 0]} name="Posts" />
                  <Bar dataKey="engagement" fill="#06b6d4" radius={[0, 4, 4, 0]} name="Engagement" />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </motion.div>
        </div>

        {/* Top Performing Posts */}
        <motion.div variants={item} className="bg-white/5 backdrop-blur-xl rounded-2xl border border-white/10 p-6">
          <h3 className="text-lg font-semibold text-white mb-4">Top Performing Content</h3>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-white/10">
                  <th className="text-left py-3 px-4 text-gray-400 font-medium text-sm">Platform</th>
                  <th className="text-left py-3 px-4 text-gray-400 font-medium text-sm">Content</th>
                  <th className="text-center py-3 px-4 text-gray-400 font-medium text-sm">Likes</th>
                  <th className="text-center py-3 px-4 text-gray-400 font-medium text-sm">Views</th>
                  <th className="text-center py-3 px-4 text-gray-400 font-medium text-sm">Shares</th>
                  <th className="text-center py-3 px-4 text-gray-400 font-medium text-sm">Engagement</th>
                </tr>
              </thead>
              <tbody>
                {topPerformingPosts.map((post) => {
                  const totalEngagement = post.engagement.likes + post.engagement.views + post.engagement.shares + post.engagement.comments;
                  const engagementRate = ((totalEngagement / post.engagement.views) * 100).toFixed(1);
                  
                  return (
                    <tr key={post.id} className="border-b border-white/5 hover:bg-white/5 transition-colors">
                      <td className="py-3 px-4">
                        <span 
                          className="px-2 py-1 rounded text-xs font-medium capitalize"
                          style={{ backgroundColor: `${platformColors[post.platform]}30`, color: platformColors[post.platform] }}
                        >
                          {post.platform}
                        </span>
                      </td>
                      <td className="py-3 px-4">
                        <p className="text-sm text-white truncate max-w-xs">{post.content}</p>
                      </td>
                      <td className="py-3 px-4 text-center">
                        <span className="text-sm text-pink-400">{post.engagement.likes.toLocaleString()}</span>
                      </td>
                      <td className="py-3 px-4 text-center">
                        <span className="text-sm text-cyan-400">{post.engagement.views.toLocaleString()}</span>
                      </td>
                      <td className="py-3 px-4 text-center">
                        <span className="text-sm text-violet-400">{post.engagement.shares.toLocaleString()}</span>
                      </td>
                      <td className="py-3 px-4 text-center">
                        <span className="text-sm font-semibold text-green-400">{engagementRate}%</span>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </motion.div>
      </div>
    </motion.div>
  );
}
